language: python
python:
  - "2.7"

before_install:
  - docker pull couchdb:latest
  - docker run -d --name couchdb -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=pass
    couchdb:latest
  - docker ps -a

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: redis-cli ping

script:
  - nosetests

after_success:
  - codecov

services:
  - redis-server
